# Generated by Django 5.2.4 on 2026-01-29 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200, null=True)),
                ("date_started", models.DateField()),
                ("date_ended", models.DateField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-current", "-date_started"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("github_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DescriptionItem",
            fields=[
                ("title", models.CharField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillItem",
            fields=[
                ("title", models.CharField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "jobs",
                    models.ManyToManyField(
                        blank=True, related_name="skills", to="core.job"
                    ),
                ),
            ],
        ),
    ]
