# Generated by Django 5.2.4 on 2026-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillitem",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="skills", to="core.project"
            ),
        ),
    ]
