# Generated by Django 5.2.4 on 2025-07-28 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DescriptionItem",
            fields=[
                ("title", models.CharField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("date_started", models.DateField()),
                ("date_ended", models.DateField(null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TodoItem",
        ),
        migrations.AddField(
            model_name="descriptionitem",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.job"
            ),
        ),
    ]
