# Generated by Django 5.2.4 on 2025-07-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_descriptionitem_job_delete_todoitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="date_ended",
            field=models.DateField(blank=True, null=True),
        ),
    ]
