# Generated by Django 5.2.4 on 2025-07-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_job_date_ended"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
