# Generated by Django 5.2.4 on 2025-08-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
