# Generated by Django 5.2.4 on 2026-01-28 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_project_github_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillItem",
            fields=[
                ("title", models.CharField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.job"
                    ),
                ),
            ],
        ),
    ]
