# Generated by Django 5.2.4 on 2026-01-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_skillitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillitem",
            name="job",
        ),
        migrations.AddField(
            model_name="skillitem",
            name="jobs",
            field=models.ManyToManyField(
                blank=True, related_name="skills", to="core.job"
            ),
        ),
    ]
