# Generated by Django 5.2.4 on 2026-01-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_skillitem_job_skillitem_jobs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-date_started"]},
        ),
    ]
