# Generated by Django 5.2.4 on 2026-01-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_job_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-date_ended", "-date_started"]},
        ),
    ]
