# Generated by Django 5.2.4 on 2026-01-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_job_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-current", "-date_started"]},
        ),
        migrations.AddField(
            model_name="job",
            name="current",
            field=models.BooleanField(default=False),
        ),
    ]
